[project]
name = "morseproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "grpcio>=1.76.0",
    "grpcio-tools>=1.76.0",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
]
